import type { Metadata } from "next";
import { Inter, Merriweather, Merriweather_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});
const merriweatherSans = Merriweather_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CafeScape Beta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={merriweather.className}>{children}</body>
    </html>
  );
}
